<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Modelo de clasificación – Minería de Datos Aplicada a México: Sistema de Transporte Colectivo</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./clustering.html" rel="next">
<link href="./eda.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7c69b197886ae2a34062761d21e44731.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-44ee0976171e9be92e6ebe9be850cd66.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./clasificacion.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelo de clasificación</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Minería de Datos Aplicada a México: Sistema de Transporte Colectivo</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Proyecto Final - Minería de Datos Aplicada a México</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Afluencia en el STC de la CDMX</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./limpieza.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Limpieza del dataset</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">EDA — Análisis Exploratorio de Datos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./clasificacion.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelo de clasificación</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Clustering — Agrupamiento de Estaciones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./arquitectura.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Arquitectura y diseño</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conclusiones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Conclusiones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#configuración-del-entorno-y-librerías" id="toc-configuración-del-entorno-y-librerías" class="nav-link active" data-scroll-target="#configuración-del-entorno-y-librerías"><span class="header-section-number">5.1</span> Configuración del entorno y librerías</a></li>
  <li><a href="#carga-de-datos-e-información-del-dataset" id="toc-carga-de-datos-e-información-del-dataset" class="nav-link" data-scroll-target="#carga-de-datos-e-información-del-dataset"><span class="header-section-number">5.2</span> Carga de datos e información del dataset</a></li>
  <li><a href="#definición-de-la-variable-objetivo-y-predictoras" id="toc-definición-de-la-variable-objetivo-y-predictoras" class="nav-link" data-scroll-target="#definición-de-la-variable-objetivo-y-predictoras"><span class="header-section-number">5.3</span> Definición de la variable objetivo y predictoras</a>
  <ul class="collapse">
  <li><a href="#variable-objetivo" id="toc-variable-objetivo" class="nav-link" data-scroll-target="#variable-objetivo"><span class="header-section-number">5.3.1</span> Variable objetivo</a></li>
  <li><a href="#variables-predictoras-incluidas" id="toc-variables-predictoras-incluidas" class="nav-link" data-scroll-target="#variables-predictoras-incluidas"><span class="header-section-number">5.3.2</span> Variables predictoras incluidas</a></li>
  <li><a href="#variables-excluidas-y-justificación" id="toc-variables-excluidas-y-justificación" class="nav-link" data-scroll-target="#variables-excluidas-y-justificación"><span class="header-section-number">5.3.3</span> Variables excluidas y justificación</a></li>
  </ul></li>
  <li><a href="#diseño-e-implementación-con-poo-patrón-strategy-y-pipeline" id="toc-diseño-e-implementación-con-poo-patrón-strategy-y-pipeline" class="nav-link" data-scroll-target="#diseño-e-implementación-con-poo-patrón-strategy-y-pipeline"><span class="header-section-number">5.4</span> Diseño e implementación con POO: Patrón Strategy y Pipeline</a></li>
  <li><a href="#división-del-conjunto-de-datos" id="toc-división-del-conjunto-de-datos" class="nav-link" data-scroll-target="#división-del-conjunto-de-datos"><span class="header-section-number">5.5</span> División del conjunto de datos</a></li>
  <li><a href="#modelo-base-baseline" id="toc-modelo-base-baseline" class="nav-link" data-scroll-target="#modelo-base-baseline"><span class="header-section-number">5.6</span> Modelo Base (Baseline)</a></li>
  <li><a href="#entrenamiento-y-ajuste-de-hiperparámetros" id="toc-entrenamiento-y-ajuste-de-hiperparámetros" class="nav-link" data-scroll-target="#entrenamiento-y-ajuste-de-hiperparámetros"><span class="header-section-number">5.7</span> Entrenamiento y Ajuste de Hiperparámetros</a></li>
  <li><a href="#análisis-de-los-hiperparámetros" id="toc-análisis-de-los-hiperparámetros" class="nav-link" data-scroll-target="#análisis-de-los-hiperparámetros"><span class="header-section-number">5.8</span> Análisis de los Hiperparámetros</a></li>
  <li><a href="#evaluación-de-rendimiento-y-métricas" id="toc-evaluación-de-rendimiento-y-métricas" class="nav-link" data-scroll-target="#evaluación-de-rendimiento-y-métricas"><span class="header-section-number">5.9</span> Evaluación de Rendimiento y Métricas</a>
  <ul class="collapse">
  <li><a href="#justificación-de-métricas-seleccionadas" id="toc-justificación-de-métricas-seleccionadas" class="nav-link" data-scroll-target="#justificación-de-métricas-seleccionadas"><span class="header-section-number">5.9.1</span> Justificación de Métricas Seleccionadas</a></li>
  <li><a href="#cálculo-y-presentación-de-métricas" id="toc-cálculo-y-presentación-de-métricas" class="nav-link" data-scroll-target="#cálculo-y-presentación-de-métricas"><span class="header-section-number">5.9.2</span> Cálculo y Presentación de Métricas</a></li>
  <li><a href="#análisis-e-interpretación-de-resultados" id="toc-análisis-e-interpretación-de-resultados" class="nav-link" data-scroll-target="#análisis-e-interpretación-de-resultados"><span class="header-section-number">5.9.3</span> Análisis e interpretación de resultados</a></li>
  </ul></li>
  <li><a href="#visualización-matriz-de-confusión-y-curva-roc" id="toc-visualización-matriz-de-confusión-y-curva-roc" class="nav-link" data-scroll-target="#visualización-matriz-de-confusión-y-curva-roc"><span class="header-section-number">5.10</span> Visualización: Matriz de Confusión y Curva ROC</a>
  <ul class="collapse">
  <li><a href="#matriz-de-confusión" id="toc-matriz-de-confusión" class="nav-link" data-scroll-target="#matriz-de-confusión"><span class="header-section-number">5.10.1</span> Matriz de Confusión</a></li>
  <li><a href="#curvas-roc-one-vs-rest-ovr" id="toc-curvas-roc-one-vs-rest-ovr" class="nav-link" data-scroll-target="#curvas-roc-one-vs-rest-ovr"><span class="header-section-number">5.10.2</span> Curvas ROC — One-vs-Rest (OvR)</a></li>
  </ul></li>
  <li><a href="#análisis-de-importancia-de-variables" id="toc-análisis-de-importancia-de-variables" class="nav-link" data-scroll-target="#análisis-de-importancia-de-variables"><span class="header-section-number">5.11</span> Análisis de Importancia de Variables</a></li>
  <li><a href="#persistencia-del-modelo-y-demostración-de-reutilización" id="toc-persistencia-del-modelo-y-demostración-de-reutilización" class="nav-link" data-scroll-target="#persistencia-del-modelo-y-demostración-de-reutilización"><span class="header-section-number">5.12</span> Persistencia del Modelo y Demostración de Reutilización</a>
  <ul class="collapse">
  <li><a href="#guardado-del-modelo" id="toc-guardado-del-modelo" class="nav-link" data-scroll-target="#guardado-del-modelo"><span class="header-section-number">5.12.1</span> Guardado del modelo</a></li>
  <li><a href="#demostración-de-reutilización-celda-independiente" id="toc-demostración-de-reutilización-celda-independiente" class="nav-link" data-scroll-target="#demostración-de-reutilización-celda-independiente"><span class="header-section-number">5.12.2</span> Demostración de reutilización (celda independiente)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelo de clasificación</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>En esta sección se construye un modelo de clasificación supervisada para predecir la variable objetivo <code>nivel_saturacion</code>, que categoriza el nivel de saturación diario de cada estación del STC Metro de la CDMX en cuatro niveles: <strong>bajo</strong> (0), <strong>medio</strong> (1), <strong>alto</strong> (2) y <strong>crítico</strong> (3). Esta variable fue definida en la etapa de preparación de datos mediante percentiles históricos de afluencia calculados de manera individual por estación, de modo que cada punto de la red se compara contra su propio historial y no contra estaciones de distinto perfil de demanda.</p>
<p>El modelo opera en un escenario de <strong>clasificación en tiempo real</strong>: dado el conteo de afluencia registrado durante el día de operación, junto con el contexto de la línea, el mes, el año y la era de pago vigente, el sistema clasifica automáticamente el nivel de saturación alcanzado. Este enfoque tiene valor operativo directo para el STC Metro, ya que automatiza la etiquetación de jornadas sin depender del cálculo manual de percentiles por estación.</p>
<p>Se empleará el algoritmo <strong>Random Forest</strong> con el <strong>Patrón de Diseño Pipeline</strong>, que encapsula las etapas de escalado y clasificación en una unidad cohesiva, serializable y reproducible. El código estará organizado mediante <strong>Programación Orientada a Objetos (POO)</strong> a través de la clase <code>ModeloClasificacion</code>, que encapsula las responsabilidades de construcción, entrenamiento, evaluación y persistencia del modelo, separando la lógica del modelo de la lógica de presentación del reporte. Los hiperparámetros se optimizarán mediante <code>RandomizedSearchCV</code> con validación cruzada estratificada interna (<code>StratifiedKFold</code>) en ejecución secuencial para garantizar la estabilidad en equipos con recursos de memoria limitados.</p>
<section id="configuración-del-entorno-y-librerías" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="configuración-del-entorno-y-librerías"><span class="header-section-number">5.1</span> Configuración del entorno y librerías</h2>
<p>Se importan todas las herramientas necesarias y se fija la semilla global <code>SEED = 42</code> para garantizar la reproducibilidad completa del experimento, como lo exigen los requisitos técnicos del proyecto.</p>
<div id="42c45c16" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>ruta_raiz <span class="op">=</span> os.path.abspath(os.path.join(os.getcwd(), <span class="st">'..'</span>, <span class="st">'..'</span>))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> ruta_raiz <span class="kw">not</span> <span class="kw">in</span> sys.path:</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    sys.path.insert(<span class="dv">0</span>, ruta_raiz)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sklearn</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> ConfusionMatrixDisplay, roc_curve, auc, roc_auc_score</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> label_binarize</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Importar la clase del modelo desde src</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> src.modelo_clasificacion <span class="im">import</span> ModeloClasificacion</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Configuración visual global</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">"whitegrid"</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> (<span class="dv">12</span>, <span class="dv">6</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'font.size'</span>] <span class="op">=</span> <span class="dv">11</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Semilla para reproducibilidad</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>SEED <span class="op">=</span> <span class="dv">42</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>np.random.seed(SEED)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Acceder a constantes desde la clase</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>NOMBRES_CLASES <span class="op">=</span> ModeloClasificacion.NOMBRES_CLASES</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>COLORES_CLASES <span class="op">=</span> ModeloClasificacion.COLORES_CLASES</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"scikit-learn : </span><span class="sc">{</span>sklearn<span class="sc">.</span>__version__<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"pandas       : </span><span class="sc">{</span>pd<span class="sc">.</span>__version__<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"numpy        : </span><span class="sc">{</span>np<span class="sc">.</span>__version__<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"seaborn      : </span><span class="sc">{</span>sns<span class="sc">.</span>__version__<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">SEED fijada  : </span><span class="sc">{</span>SEED<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>scikit-learn : 1.9.0
pandas       : 3.0.3
numpy        : 2.4.6
seaborn      : 0.13.2

SEED fijada  : 42</code></pre>
</div>
</div>
</section>
<section id="carga-de-datos-e-información-del-dataset" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="carga-de-datos-e-información-del-dataset"><span class="header-section-number">5.2</span> Carga de datos e información del dataset</h2>
<p>Se carga el archivo <code>df_clasificacion.csv</code> generado en la etapa de limpieza. Este dataset contiene únicamente las columnas seleccionadas para el modelo supervisado y ya fue sometido a los tratamientos documentados en <code>limpieza.qmd</code>: eliminación de registros con afluencia cero durante los cierres documentados de Líneas 1 y 12, cálculo de percentiles históricos por estación y codificación numérica de variables categóricas con <code>LabelEncoder</code>.</p>
<div id="46a7a8fb" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"../../data/processed/df_clasificacion.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">" Información general del dataset "</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Dimensiones : </span><span class="sc">{</span>df<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">:,}</span><span class="ss"> registros  ×  </span><span class="sc">{</span>df<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> variables"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Columnas    : </span><span class="sc">{</span>df<span class="sc">.</span>columns<span class="sc">.</span>tolist()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st"> Primeros 5 registros "</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.head())</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st"> Tipos de datos "</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.dtypes)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st"> Valores faltantes "</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>nulos <span class="op">=</span> df.isnull().<span class="bu">sum</span>()</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(nulos[nulos <span class="op">&gt;</span> <span class="dv">0</span>] <span class="cf">if</span> nulos.<span class="bu">any</span>() <span class="cf">else</span> <span class="st">"  Sin valores faltantes."</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st"> Estadísticas descriptivas "</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.describe().<span class="bu">round</span>(<span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> Información general del dataset 
  Dimensiones : 358,086 registros  ×  10 variables
  Columnas    : ['linea_encoded', 'estacion_encoded', 'dia_semana', 'mes_encoded', 'anio', 'es_festivo', 'es_quincena', 'lluvia_historica', 'post_boleto', 'nivel_saturacion']

 Primeros 5 registros 
   linea_encoded  estacion_encoded  dia_semana  mes_encoded  anio  es_festivo  \
0              0                10           4            3  2021           0   
1              0                11           4            3  2021           0   
2              0                16           4            3  2021           0   
3              0                22           4            3  2021           0   
4              0                26           4            3  2021           0   

   es_quincena  lluvia_historica  post_boleto  nivel_saturacion  
0            0                 0            0                 0  
1            0                 0            0                 0  
2            0                 0            0                 0  
3            0                 0            0                 0  
4            0                 0            0                 1  

 Tipos de datos 
linea_encoded       int64
estacion_encoded    int64
dia_semana          int64
mes_encoded         int64
anio                int64
es_festivo          int64
es_quincena         int64
lluvia_historica    int64
post_boleto         int64
nivel_saturacion    int64
dtype: object

 Valores faltantes 
  Sin valores faltantes.

 Estadísticas descriptivas 
       linea_encoded  estacion_encoded  dia_semana  mes_encoded       anio  \
count      358086.00         358086.00    358086.0    358086.00  358086.00   
mean            5.34             79.46         3.0         5.36    2023.25   
std             3.57             46.50         2.0         3.43       1.56   
min             0.00              0.00         0.0         0.00    2021.00   
25%             2.00             39.00         1.0         2.00    2022.00   
50%             5.00             78.00         3.0         5.00    2023.00   
75%             8.00            120.00         5.0         8.00    2025.00   
max            11.00            162.00         6.0        11.00    2026.00   

       es_festivo  es_quincena  lluvia_historica  post_boleto  \
count    358086.0    358086.00         358086.00    358086.00   
mean          0.0         0.11              0.47         0.40   
std           0.0         0.32              0.50         0.49   
min           0.0         0.00              0.00         0.00   
25%           0.0         0.00              0.00         0.00   
50%           0.0         0.00              0.00         0.00   
75%           0.0         0.00              1.00         1.00   
max           0.0         1.00              1.00         1.00   

       nivel_saturacion  
count         358086.00  
mean               1.30  
std                1.01  
min                0.00  
25%                0.00  
50%                1.00  
75%                2.00  
max                3.00  </code></pre>
</div>
</div>
</section>
<section id="definición-de-la-variable-objetivo-y-predictoras" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="definición-de-la-variable-objetivo-y-predictoras"><span class="header-section-number">5.3</span> Definición de la variable objetivo y predictoras</h2>
<section id="variable-objetivo" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="variable-objetivo"><span class="header-section-number">5.3.1</span> Variable objetivo</h3>
<p>La variable <code>nivel_saturacion</code> es el objetivo de predicción. Toma cuatro valores enteros que representan el nivel de saturación diario de una estación medido contra su historial propio:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Valor</th>
<th>Etiqueta</th>
<th>Definición</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><strong>Bajo</strong></td>
<td>Afluencia ≤ percentil 25 histórico</td>
</tr>
<tr class="even">
<td>1</td>
<td><strong>Medio</strong></td>
<td>p25 &lt; Afluencia ≤ percentil 60</td>
</tr>
<tr class="odd">
<td>2</td>
<td><strong>Alto</strong></td>
<td>p60 &lt; Afluencia ≤ percentil 85</td>
</tr>
<tr class="even">
<td>3</td>
<td><strong>Crítico</strong></td>
<td>Afluencia &gt; percentil 85</td>
</tr>
</tbody>
</table>
<p>Esta variable es la más adecuada para el objetivo del proyecto porque operacionaliza directamente el concepto de <strong>saturación relativa</strong> en lugar de absoluta: una afluencia de 5 000 pasajeros puede ser crítica para una estación pequeña de Línea B y completamente normal para una estación central de Línea 2. Al construirla desde los percentiles individuales de cada estación, el modelo aprende patrones de demanda que son comparables y generalizables a través de toda la red del STC.</p>
<div id="41143e04" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">'nivel_saturacion'</span>]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Distribución de la variable objetivo:"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>counts      <span class="op">=</span> y.value_counts().sort_index()</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>percentages <span class="op">=</span> y.value_counts(normalize<span class="op">=</span><span class="va">True</span>).sort_index() <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">4</span>):</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  Clase </span><span class="sc">{</span>i<span class="sc">}</span><span class="ss"> – </span><span class="sc">{</span>NOMBRES_CLASES[i]<span class="sc">:8s}</span><span class="ss">: </span><span class="sc">{</span>counts[i]<span class="sc">:8,}</span><span class="ss"> registros  (</span><span class="sc">{</span>percentages[i]<span class="sc">:.2f}</span><span class="ss">%)"</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualización</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> [<span class="ss">f"</span><span class="sc">{</span>NOMBRES_CLASES[i]<span class="sc">}</span><span class="ch">\n</span><span class="ss">(clase </span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">)"</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">4</span>)]</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">5</span>))</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].bar(labels, counts.values, color<span class="op">=</span>COLORES_CLASES, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">'Distribución de nivel_saturacion'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">'Nivel de saturación'</span>)<span class="op">;</span> axes[<span class="dv">0</span>].set_ylabel(<span class="st">'Frecuencia'</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, (v, pct) <span class="kw">in</span> <span class="bu">enumerate</span>(<span class="bu">zip</span>(counts.values, percentages.values)):</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].text(i, v <span class="op">+</span> counts.<span class="bu">max</span>()<span class="op">*</span><span class="fl">0.01</span>, <span class="ss">f"</span><span class="sc">{</span>pct<span class="sc">:.1f}</span><span class="ss">%"</span>,</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>                 ha<span class="op">=</span><span class="st">'center'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].pie(counts.values, labels<span class="op">=</span>labels, colors<span class="op">=</span>COLORES_CLASES,</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>            autopct<span class="op">=</span><span class="st">'</span><span class="sc">%1.1f%%</span><span class="st">'</span>, startangle<span class="op">=</span><span class="dv">90</span>, pctdistance<span class="op">=</span><span class="fl">0.75</span>)</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">'Proporción de nivel_saturacion'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Distribución de la variable objetivo:
  Clase 0 – Bajo    :   90,694 registros  (25.33%)
  Clase 1 – Medio   :  124,242 registros  (34.70%)
  Clase 2 – Alto    :   89,437 registros  (24.98%)
  Clase 3 – Crítico :   53,713 registros  (15.00%)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="clasificacion_files/figure-html/cell-4-output-2.png" width="1237" height="464" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>La distribución resulta de los umbrales percentílicos fijados en la etapa de limpieza. Cada clase agrupa los días cuya afluencia diaria cae dentro del rango correspondiente al historial propio de la estación:</p>
<ul>
<li><strong>Bajo (~25 %):</strong> días de baja demanda, con afluencia por debajo del primer cuartil histórico de cada estación.</li>
<li><strong>Medio (~35 %):</strong> franja de operación normal, entre los percentiles 25 y 60; es la clase mayoritaria del dataset.</li>
<li><strong>Alto (~25 %):</strong> demanda elevada, entre los percentiles 60 y 85.</li>
<li><strong>Crítico (~15 %):</strong> jornadas de máxima saturación, con afluencia por encima del percentil 85; es la clase menos frecuente.</li>
</ul>
<p>El desbalance leve (especialmente la menor representación de Crítico) justifica el uso de <code>class_weight='balanced'</code> en el clasificador, pues nos garantiza que el modelo preste atención a las clases menos frecuentes durante el entrenamiento, asignándoles un peso inversamente proporcional a su frecuencia, en este caso nos resulta útil para nuestra clase Crítico y su representación del 15 % (la clase con menor frecuencia dentro de nuestro dataset).</p>
</section>
<section id="variables-predictoras-incluidas" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="variables-predictoras-incluidas"><span class="header-section-number">5.3.2</span> Variables predictoras incluidas</h3>
<div id="f4e93d32" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df.drop(<span class="st">'nivel_saturacion'</span>, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Total de features : </span><span class="sc">{</span>X<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Variables         : </span><span class="sc">{</span>X<span class="sc">.</span>columns<span class="sc">.</span>tolist()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>linea_mapping <span class="op">=</span> ModeloClasificacion.LINEA_MAPPING</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>mes_mapping   <span class="op">=</span> ModeloClasificacion.MES_MAPPING</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Total de features : 9
Variables         : ['linea_encoded', 'estacion_encoded', 'dia_semana', 'mes_encoded', 'anio', 'es_festivo', 'es_quincena', 'lluvia_historica', 'post_boleto']</code></pre>
</div>
</div>
<p>Las nueve variables predictoras empleadas en el modelo y su justificación son las siguientes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Descripción y justificación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>linea_encoded</code></td>
<td>Línea del STC codificada con LabelEncoder (0–11). Cada línea tiene un perfil de demanda estructuralmente distinto según su recorrido y zona de la ciudad.</td>
</tr>
<tr class="even">
<td><code>estacion_encoded</code></td>
<td>Identificador único de la estación (LabelEncoder). Es vital para el modelo ya que la saturación es un concepto relativo: permite al clasificador aislar la escala física e infraestructura de cada andén.</td>
</tr>
<tr class="odd">
<td><code>dia_semana</code></td>
<td>Día de la semana extraído de la fecha (0=Lunes, 6=Domingo). Captura los patrones de movilidad intra-semanales, diferenciando la alta demanda en días laborales de las caídas en fines de semana.</td>
</tr>
<tr class="even">
<td><code>mes_encoded</code></td>
<td>Mes del año codificado con LabelEncoder (0–11, orden alfabético). Captura la estacionalidad: inicio de semestres (ene, ago) frente a periodos vacacionales (dic, jul).</td>
</tr>
<tr class="odd">
<td><code>anio</code></td>
<td>Año de la medición (2021–2026). Registra la tendencia longitudinal del sistema: recuperación post-COVID, cierres de líneas y crecimiento posterior.</td>
</tr>
<tr class="even">
<td><code>es_festivo</code></td>
<td>Variable binaria (1=Festivo, 0=Laborable). Captura caídas drásticas de demanda en días feriados oficiales.</td>
</tr>
<tr class="odd">
<td><code>es_quincena</code></td>
<td>Variable binaria para días 14, 15, 30 y 31. Modela los picos de movilidad asociados a las dinámicas económicas y de consumo en la ciudad.</td>
</tr>
<tr class="even">
<td><code>lluvia_historica</code></td>
<td>Variable binaria (1=Mayo–Octubre, 0=Resto). Indica la temporada de lluvias en la CDMX, factor climático que históricamente incrementa el uso del transporte subterráneo.</td>
</tr>
<tr class="odd">
<td><code>post_boleto</code></td>
<td>Indicador binario del cambio de método de pago (0 = antes del 20-abr-2024, 1 = después). Controla si la transición al prepago exclusivo alteró los flujos de entrada en las estaciones.</td>
</tr>
</tbody>
</table>
</section>
<section id="variables-excluidas-y-justificación" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="variables-excluidas-y-justificación"><span class="header-section-number">5.3.3</span> Variables excluidas y justificación</h3>
<p>El dataset de clasificación fue construido a partir de un dataset intermedio más amplio que también contenía las siguientes columnas, las cuales fueron deliberadamente excluidas del modelo supervisado por las razones que se describen a continuación:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variable excluida</th>
<th>Motivo de exclusión</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>fecha</code></td>
<td>Su información temporal ya está capturada de forma modelable por <code>dia_semana</code>, <code>mes_encoded</code>, <code>anio</code> y <code>post_boleto</code>. En formato datetime no es compatible con scikit-learn.</td>
</tr>
<tr class="even">
<td><code>linea</code> (texto crudo)</td>
<td>Variable categórica original reemplazada por <code>linea_encoded</code> (LabelEncoder), compatible con scikit-learn.</td>
</tr>
<tr class="odd">
<td><code>estacion</code> (texto crudo)</td>
<td>Variable categórica original reemplazada por <code>estacion_encoded</code>.</td>
</tr>
<tr class="even">
<td><code>mes</code> (texto crudo)</td>
<td>Variable categórica original reemplazada por <code>mes_encoded</code>.</td>
</tr>
<tr class="odd">
<td><code>afluencia_boleto</code>, <code>afluencia_prepago</code>, <code>afluencia_gratuidad</code></td>
<td>Las tres suman exactamente <code>afluencia_total</code>, generando <strong>multicolinealidad perfecta</strong>. Incluirlas sería redundante e inflaría artificialmente el espacio de features.</td>
</tr>
<tr class="even">
<td><code>p25</code>, <code>p60</code>, <code>p85</code></td>
<td>Son los percentiles históricos utilizados para <strong>construir</strong> <code>nivel_saturacion</code>. Incluirlos como predictores constituiría <strong>filtración de datos (data leakage)</strong>.</td>
</tr>
<tr class="odd">
<td><code>afluencia_total</code></td>
<td><strong>Excluida para evitar Filtración de Datos (Data Leakage Crítico):</strong> Dado que la variable objetivo se deriva matemáticamente de esta métrica, mantenerla provocaría que el algoritmo memorice reglas de umbrales condicionales directos en lugar de aprender el comportamiento del sistema. Su eliminación eleva la complejidad del problema, forzando al modelo a aprender patrones puramente contextuales.</td>
</tr>
</tbody>
</table>
<div id="f00b8e94" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualización de distribuciones de las 9 variables predictoras</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">18</span>, <span class="dv">14</span>)) <span class="co"># Cambiado a 3x3 y un poco más alto</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>axes <span class="op">=</span> axes.flatten()</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. estacion_encoded</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].hist(X[<span class="st">'estacion_encoded'</span>], bins<span class="op">=</span><span class="dv">50</span>, color<span class="op">=</span><span class="st">'steelblue'</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>             edgecolor<span class="op">=</span><span class="st">'white'</span>, alpha<span class="op">=</span><span class="fl">0.85</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">'Distribución: estacion_encoded'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">'ID Estación'</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">'Frecuencia'</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. linea_encoded</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>lc <span class="op">=</span> X[<span class="st">'linea_encoded'</span>].value_counts().sort_index()</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].bar(<span class="bu">range</span>(<span class="bu">len</span>(lc)), lc.values, color<span class="op">=</span><span class="st">'steelblue'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">'Distribución: linea_encoded'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticks(<span class="bu">range</span>(<span class="bu">len</span>(lc)))</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticklabels([linea_mapping.get(i, <span class="bu">str</span>(i)) <span class="cf">for</span> i <span class="kw">in</span> lc.index],</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>                         rotation<span class="op">=</span><span class="dv">45</span>, ha<span class="op">=</span><span class="st">'right'</span>, fontsize<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. dia_semana</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>ds <span class="op">=</span> X[<span class="st">'dia_semana'</span>].value_counts().sort_index()</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].bar(<span class="bu">range</span>(<span class="bu">len</span>(ds)), ds.values, color<span class="op">=</span><span class="st">'steelblue'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_title(<span class="st">'Distribución: dia_semana'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_xticks(<span class="bu">range</span>(<span class="bu">len</span>(ds)))</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_xticklabels([<span class="st">'Lun'</span>, <span class="st">'Mar'</span>, <span class="st">'Mié'</span>, <span class="st">'Jue'</span>, <span class="st">'Vie'</span>, <span class="st">'Sáb'</span>, <span class="st">'Dom'</span>])</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. mes_encoded</span></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>mc <span class="op">=</span> X[<span class="st">'mes_encoded'</span>].value_counts().sort_index()</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">3</span>].bar(<span class="bu">range</span>(<span class="bu">len</span>(mc)), mc.values, color<span class="op">=</span><span class="st">'steelblue'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">3</span>].set_title(<span class="st">'Distribución: mes_encoded'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">3</span>].set_xticks(<span class="bu">range</span>(<span class="bu">len</span>(mc)))</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">3</span>].set_xticklabels([mes_mapping.get(i, <span class="bu">str</span>(i)) <span class="cf">for</span> i <span class="kw">in</span> mc.index],</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>                          rotation<span class="op">=</span><span class="dv">45</span>, ha<span class="op">=</span><span class="st">'right'</span>, fontsize<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. anio</span></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>ac <span class="op">=</span> X[<span class="st">'anio'</span>].value_counts().sort_index()</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">4</span>].bar(ac.index.astype(<span class="bu">str</span>), ac.values, color<span class="op">=</span><span class="st">'steelblue'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">4</span>].set_title(<span class="st">'Distribución: anio'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a><span class="co"># 6. post_boleto</span></span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>pb <span class="op">=</span> X[<span class="st">'post_boleto'</span>].value_counts().sort_index()</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">5</span>].bar([<span class="st">'Pre (0)'</span>, <span class="st">'Post (1)'</span>], pb.values, color<span class="op">=</span>[<span class="st">'#3498db'</span>, <span class="st">'#e74c3c'</span>], edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">5</span>].set_title(<span class="st">'Distribución: post_boleto'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a><span class="co"># 7. es_festivo</span></span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>fest <span class="op">=</span> X[<span class="st">'es_festivo'</span>].value_counts().sort_index()</span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">6</span>].bar([<span class="st">'Laborable (0)'</span>, <span class="st">'Festivo (1)'</span>], fest.values, color<span class="op">=</span>[<span class="st">'#95a5a6'</span>, <span class="st">'#f39c12'</span>], edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">6</span>].set_title(<span class="st">'Distribución: es_festivo'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a><span class="co"># 8. es_quincena</span></span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a>quin <span class="op">=</span> X[<span class="st">'es_quincena'</span>].value_counts().sort_index()</span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">7</span>].bar([<span class="st">'No Quincena (0)'</span>, <span class="st">'Quincena (1)'</span>], quin.values, color<span class="op">=</span>[<span class="st">'#95a5a6'</span>, <span class="st">'#2ecc71'</span>], edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">7</span>].set_title(<span class="st">'Distribución: es_quincena'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a><span class="co"># 9. lluvia_historica</span></span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a>lluvia <span class="op">=</span> X[<span class="st">'lluvia_historica'</span>].value_counts().sort_index()</span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">8</span>].bar([<span class="st">'Seca (0)'</span>, <span class="st">'Lluvias (1)'</span>], lluvia.values, color<span class="op">=</span>[<span class="st">'#f1c40f'</span>, <span class="st">'#3498db'</span>], edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">8</span>].set_title(<span class="st">'Distribución: lluvia_historica'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-60"><a href="#cb9-60" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">'Distribución de las 9 variables predictoras incluidas en el modelo'</span>,</span>
<span id="cb9-61"><a href="#cb9-61" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">16</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, y<span class="op">=</span><span class="fl">1.02</span>)</span>
<span id="cb9-62"><a href="#cb9-62" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb9-63"><a href="#cb9-63" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="clasificacion_files/figure-html/cell-6-output-1.png" width="1714" height="1373" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="diseño-e-implementación-con-poo-patrón-strategy-y-pipeline" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="diseño-e-implementación-con-poo-patrón-strategy-y-pipeline"><span class="header-section-number">5.4</span> Diseño e implementación con POO: Patrón Strategy y Pipeline</h2>
<p>El código fuente del modelo está organizado mediante <strong>Programación Orientada a Objetos (POO)</strong>. Para esta etapa, se implementó una arquitectura basada en el <strong>Patrón de Diseño Strategy</strong> mediante una clase abstracta padre (<code>ModeloBase</code>), de la cual hereda nuestra clase concreta <code>ModeloClasificacion</code>. Esta arquitectura permite intercambiar algoritmos estandarizando métodos clave como <code>entrenar()</code>, <code>predecir()</code> y la persistencia (<code>guardar_modelo()</code> y <code>cargar_modelo()</code>).</p>
<p>A nivel de procesamiento de datos, se emplea el <strong>Patrón Pipeline</strong> de scikit-learn. El procesamiento ocurre en etapas secuenciales bien definidas (normalización con <code>StandardScaler</code> → clasificación con <code>RandomForestClassifier</code>), lo que permite encapsular ambas transformaciones en un único objeto cohesivo, serializable y reproducible.</p>
<p>La clase implementa los siguientes métodos organizados por responsabilidad:</p>
<ul>
<li><strong>Construcción</strong>: <code>_construir_pipeline_base()</code> — crea un Pipeline limpio sin ajustar.</li>
<li><strong>Entrenamiento</strong>: <code>entrenar()</code> — búsqueda con <code>RandomizedSearchCV</code> + <code>StratifiedKFold</code>.</li>
<li><strong>Predicción</strong>: <code>predecir()</code> y <code>predecir_proba()</code> — inferencia sobre nuevas observaciones.</li>
<li><strong>Evaluación</strong>: <code>evaluar()</code> — calcula el conjunto completo de métricas requeridas.</li>
<li><strong>Análisis</strong>: <code>importancia_variables()</code> y <code>resultados_busqueda()</code> — introspección del modelo.</li>
<li><strong>Persistencia</strong>: <code>guardar_modelo()</code> y <code>cargar_modelo()</code> — serialización y deserialización con joblib.</li>
</ul>
<div id="f1d1709d" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Instanciación del modelo</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="op">=</span> ModeloClasificacion(seed<span class="op">=</span>SEED)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Modelo de clasificación importado desde src.modelo_clasificacion"</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span>modelo<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Métodos disponibles:"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>metodos <span class="op">=</span> [m <span class="cf">for</span> m <span class="kw">in</span> <span class="bu">dir</span>(modelo) <span class="cf">if</span> <span class="kw">not</span> m.startswith(<span class="st">'_'</span>) <span class="kw">or</span> m <span class="op">==</span> <span class="st">'__repr__'</span>]</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> m <span class="kw">in</span> metodos:</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> m.startswith(<span class="st">'_'</span>):</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"  - </span><span class="sc">{</span>m<span class="sc">}</span><span class="ss">()"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Modelo de clasificación importado desde src.modelo_clasificacion

Modelo: ModeloClasificacion, Estado: No entrenado, Características: None

Métodos disponibles:
  - COLORES_CLASES()
  - DEFAULT_PARAM_DISTRIBUTIONS()
  - LINEA_MAPPING()
  - MES_MAPPING()
  - NOMBRES_CLASES()
  - accuracy_entrenamiento()
  - baseline_dummy()
  - busqueda_()
  - cargar_modelo()
  - entrenar()
  - evaluar()
  - feature_names_()
  - guardar_modelo()
  - importancia_variables()
  - obtener_info_modelo()
  - pipeline_()
  - predecir()
  - predecir_proba()
  - resultados_busqueda()
  - seed()</code></pre>
</div>
</div>
<p>La clase <code>ModeloClasificacion</code> queda instanciada con <code>seed=42</code>. Los métodos públicos disponibles son: <code>entrenar()</code>, <code>cargar_modelo()</code> (classmethod), <code>evaluar()</code>, <code>guardar_modelo()</code>, <code>importancia_variables()</code>, <code>predecir()</code>, <code>predecir_proba()</code> y <code>resultados_busqueda()</code>.</p>
</section>
<section id="división-del-conjunto-de-datos" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="división-del-conjunto-de-datos"><span class="header-section-number">5.5</span> División del conjunto de datos</h2>
<p>Se divide el dataset en entrenamiento (80 %) y prueba (20 %) con <code>stratify=y</code> para mantener la proporción de cada clase en ambos subconjuntos. La semilla fija garantiza la reproducibilidad del experimento.</p>
<div id="e3183c5b" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    X, y,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    test_size<span class="op">=</span><span class="fl">0.2</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span>SEED,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    stratify<span class="op">=</span>y</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Conjunto de ENTRENAMIENTO : </span><span class="sc">{</span>X_train<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">:,}</span><span class="ss"> registros  (</span><span class="sc">{</span>X_train<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="op">/</span><span class="bu">len</span>(X)<span class="op">*</span><span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">%)"</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Conjunto de PRUEBA        : </span><span class="sc">{</span>X_test<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">:,}</span><span class="ss"> registros  (</span><span class="sc">{</span>X_test<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="op">/</span><span class="bu">len</span>(X)<span class="op">*</span><span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">%)"</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Variables                 : </span><span class="sc">{</span>X_train<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Distribución de clases — ENTRENAMIENTO:"</span>)</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">4</span>):</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> (y_train <span class="op">==</span> i).<span class="bu">sum</span>()</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>NOMBRES_CLASES[i]<span class="sc">:8s}</span><span class="ss"> (clase </span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">): </span><span class="sc">{</span>n<span class="sc">:7,}</span><span class="ss">  (</span><span class="sc">{</span><span class="dv">100</span><span class="op">*</span>n<span class="op">/</span><span class="bu">len</span>(y_train)<span class="sc">:.1f}</span><span class="ss">%)"</span>)</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Distribución de clases — PRUEBA:"</span>)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">4</span>):</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> (y_test <span class="op">==</span> i).<span class="bu">sum</span>()</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>NOMBRES_CLASES[i]<span class="sc">:8s}</span><span class="ss"> (clase </span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">): </span><span class="sc">{</span>n<span class="sc">:7,}</span><span class="ss">  (</span><span class="sc">{</span><span class="dv">100</span><span class="op">*</span>n<span class="op">/</span><span class="bu">len</span>(y_test)<span class="sc">:.1f}</span><span class="ss">%)"</span>)</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st"> Estratificación verificada: proporciones equivalentes en ambos conjuntos."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Conjunto de ENTRENAMIENTO : 286,468 registros  (80%)
Conjunto de PRUEBA        : 71,618 registros  (20%)
Variables                 : 9

Distribución de clases — ENTRENAMIENTO:
  Bajo     (clase 0):  72,555  (25.3%)
  Medio    (clase 1):  99,393  (34.7%)
  Alto     (clase 2):  71,550  (25.0%)
  Crítico  (clase 3):  42,970  (15.0%)

Distribución de clases — PRUEBA:
  Bajo     (clase 0):  18,139  (25.3%)
  Medio    (clase 1):  24,849  (34.7%)
  Alto     (clase 2):  17,887  (25.0%)
  Crítico  (clase 3):  10,743  (15.0%)

 Estratificación verificada: proporciones equivalentes en ambos conjuntos.</code></pre>
</div>
</div>
<p>La estratificación con <code>stratify=y</code> garantiza que las proporciones de cada clase son equivalentes en entrenamiento y prueba, asegurando que la clase Crítico (~15 %) esté representada en ambos subconjuntos sin sesgo de muestreo.</p>
<p>La elección de la proporción 80/20 se justifica por la naturaleza del dataset: un conjunto de entrenamiento más grande permite al modelo aprender los patrones de afluencia de todas las líneas y estaciones con mejor cobertura temporal, mientras que un conjunto de prueba del 20 % es suficientemente grande para obtener una evaluación estadísticamente robusta. El uso de <code>stratify=y</code> garantiza que la clase minoritaria (Crítico, ~15 %) esté representada en ambos subconjuntos en la misma proporción, evitando sesgos en la evaluación.</p>
</section>
<section id="modelo-base-baseline" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="modelo-base-baseline"><span class="header-section-number">5.6</span> Modelo Base (Baseline)</h2>
<p>Se entrena un <code>DummyClassifier</code> con la estrategia <code>most_frequent</code>, que predice siempre la clase más frecuente del conjunto de entrenamiento. Este clasificador trivial establece el umbral mínimo de <em>Accuracy</em> que el modelo real está obligado a superar para justificar su complejidad computacional.</p>
<div id="1b45e29c" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Se calcula el accuracy de la línea base usando el método encapsulado</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>dummy_acc <span class="op">=</span> modelo.baseline_dummy(X_train, y_train, X_test, y_test)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Para saber cuál fue la clase más frecuente simplemente vemos y_train</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>clase_mayoritaria_idx <span class="op">=</span> y_train.mode()[<span class="dv">0</span>]</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>clase_mas_frecuente <span class="op">=</span> NOMBRES_CLASES[clase_mayoritaria_idx]</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Clasificador Trivial (DummyClassifier — most_frequent)"</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">  Estrategia                 : Predecir siempre la clase '</span><span class="sc">{</span>clase_mas_frecuente<span class="sc">}</span><span class="ss">'"</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Accuracy en prueba         : </span><span class="sc">{</span>dummy_acc<span class="sc">:.4f}</span><span class="ss">  (</span><span class="sc">{</span>dummy_acc<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%)"</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">  → El modelo supervisado debe superar </span><span class="sc">{</span>dummy_acc<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">% de accuracy"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Clasificador Trivial (DummyClassifier — most_frequent)

  Estrategia                 : Predecir siempre la clase 'Medio'
  Accuracy en prueba         : 0.3470  (34.70%)

  → El modelo supervisado debe superar 34.70% de accuracy</code></pre>
</div>
</div>
</section>
<section id="entrenamiento-y-ajuste-de-hiperparámetros" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="entrenamiento-y-ajuste-de-hiperparámetros"><span class="header-section-number">5.7</span> Entrenamiento y Ajuste de Hiperparámetros</h2>
<p>Se construye el <strong>Patrón Pipeline</strong> a través del método <code>_construir_pipeline_base()</code> de la clase <code>ModeloClasificacion</code>. Este patrón encadena dos etapas secuenciales bien definidas: <code>StandardScaler</code> (normalización de variables) y <code>RandomForestClassifier</code> (clasificación multiclase). Al elegir el Patrón Pipeline se garantiza que la misma transformación de normalización aprendida en entrenamiento se aplique automáticamente en cada predicción futura, eliminando el riesgo de inconsistencias entre etapas.</p>
<p>La búsqueda de hiperparámetros se realiza mediante <code>RandomizedSearchCV</code>, que evalúa un número fijo de combinaciones aleatorias del espacio de parámetros (más eficiente que <code>GridSearchCV</code> para espacios grandes). La evaluación de cada combinación se realiza con <strong>validación cruzada estratificada interna</strong> (<code>StratifiedKFold</code>, 3 pliegues), garantizando que la proporción de clases se mantenga en cada pliegue. La ejecución es <strong>secuencial</strong> (<code>n_jobs=None</code>) para evitar desbordamiento de memoria.</p>
<p>El espacio de búsqueda explorado es el siguiente:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Hiperparámetro</th>
<th>Valores candidatos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>n_estimators</code></td>
<td>150, 200, 300</td>
</tr>
<tr class="even">
<td><code>max_depth</code></td>
<td>20, 30, 40, None</td>
</tr>
<tr class="odd">
<td><code>min_samples_split</code></td>
<td>2, 5</td>
</tr>
<tr class="even">
<td><code>min_samples_leaf</code></td>
<td>1, 2</td>
</tr>
<tr class="odd">
<td><code>max_features</code></td>
<td><code>'sqrt'</code>, <code>'log2'</code></td>
</tr>
</tbody>
</table>
<p>La búsqueda evalúa <strong>10 combinaciones aleatorias</strong> con <strong>3 pliegues</strong> de validación cruzada estratificada interna (<code>StratifiedKFold</code>), lo que implica 30 ajustes en total. La métrica de optimización es <code>f1_macro</code> y la ejecución es secuencial (<code>n_jobs=None</code>) para evitar desbordamiento de memoria.</p>
<div id="9b973cdd" class="cell" data-cache="true" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Espacio de búsqueda y configuración del Pipeline"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Espacio de búsqueda definido:"</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> param, valores <span class="kw">in</span> ModeloClasificacion.DEFAULT_PARAM_DISTRIBUTIONS.items():</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>param<span class="sc">:&lt;47}</span><span class="ss">: </span><span class="sc">{</span>valores<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Iniciando búsqueda de hiperparámetros..."</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"─"</span> <span class="op">*</span> <span class="dv">60</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>resultado_busqueda <span class="op">=</span> modelo.entrenar(</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    X_train<span class="op">=</span>X_train,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    y_train<span class="op">=</span>y_train,</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    n_iter<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    n_splits<span class="op">=</span><span class="dv">3</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Búsqueda completada en </span><span class="sc">{</span>resultado_busqueda[<span class="st">'tiempo_seg'</span>]<span class="sc">:.1f}</span><span class="ss"> segundos."</span>)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Mejor F1 macro (CV interna): </span><span class="sc">{</span>resultado_busqueda[<span class="st">'mejor_score_f1'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Mejores hiperparámetros encontrados:"</span>)</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> param, valor <span class="kw">in</span> resultado_busqueda[<span class="st">'mejores_params'</span>].items():</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>param<span class="sc">.</span>replace(<span class="st">'clasificador__'</span>, <span class="st">''</span>)<span class="sc">:&lt;25}</span><span class="ss">: </span><span class="sc">{</span>valor<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Espacio de búsqueda y configuración del Pipeline

Espacio de búsqueda definido:
  clasificador__n_estimators                     : [150, 200, 300]
  clasificador__max_depth                        : [20, 30, 40, None]
  clasificador__min_samples_split                : [2, 5]
  clasificador__min_samples_leaf                 : [1, 2]
  clasificador__max_features                     : ['sqrt', 'log2']

Iniciando búsqueda de hiperparámetros...
────────────────────────────────────────────────────────────
Fitting 3 folds for each of 10 candidates, totalling 30 fits
[CV] END clasificador__max_depth=None, clasificador__max_features=sqrt, clasificador__min_samples_leaf=2, clasificador__min_samples_split=2, clasificador__n_estimators=300; total time= 1.3min
[CV] END clasificador__max_depth=None, clasificador__max_features=sqrt, clasificador__min_samples_leaf=2, clasificador__min_samples_split=2, clasificador__n_estimators=300; total time= 1.3min
[CV] END clasificador__max_depth=None, clasificador__max_features=sqrt, clasificador__min_samples_leaf=2, clasificador__min_samples_split=2, clasificador__n_estimators=300; total time= 1.2min
[CV] END clasificador__max_depth=None, clasificador__max_features=sqrt, clasificador__min_samples_leaf=1, clasificador__min_samples_split=5, clasificador__n_estimators=300; total time= 1.3min
[CV] END clasificador__max_depth=None, clasificador__max_features=sqrt, clasificador__min_samples_leaf=1, clasificador__min_samples_split=5, clasificador__n_estimators=300; total time= 1.0min
[CV] END clasificador__max_depth=None, clasificador__max_features=sqrt, clasificador__min_samples_leaf=1, clasificador__min_samples_split=5, clasificador__n_estimators=300; total time=  59.5s
[CV] END clasificador__max_depth=None, clasificador__max_features=sqrt, clasificador__min_samples_leaf=1, clasificador__min_samples_split=2, clasificador__n_estimators=200; total time=  47.1s
[CV] END clasificador__max_depth=None, clasificador__max_features=sqrt, clasificador__min_samples_leaf=1, clasificador__min_samples_split=2, clasificador__n_estimators=200; total time=  50.9s
[CV] END clasificador__max_depth=None, clasificador__max_features=sqrt, clasificador__min_samples_leaf=1, clasificador__min_samples_split=2, clasificador__n_estimators=200; total time=  44.7s
[CV] END clasificador__max_depth=None, clasificador__max_features=log2, clasificador__min_samples_leaf=2, clasificador__min_samples_split=5, clasificador__n_estimators=200; total time=  41.0s
[CV] END clasificador__max_depth=None, clasificador__max_features=log2, clasificador__min_samples_leaf=2, clasificador__min_samples_split=5, clasificador__n_estimators=200; total time=  37.6s
[CV] END clasificador__max_depth=None, clasificador__max_features=log2, clasificador__min_samples_leaf=2, clasificador__min_samples_split=5, clasificador__n_estimators=200; total time=  36.7s
[CV] END clasificador__max_depth=30, clasificador__max_features=sqrt, clasificador__min_samples_leaf=2, clasificador__min_samples_split=5, clasificador__n_estimators=150; total time=  27.9s
[CV] END clasificador__max_depth=30, clasificador__max_features=sqrt, clasificador__min_samples_leaf=2, clasificador__min_samples_split=5, clasificador__n_estimators=150; total time=  27.8s
[CV] END clasificador__max_depth=30, clasificador__max_features=sqrt, clasificador__min_samples_leaf=2, clasificador__min_samples_split=5, clasificador__n_estimators=150; total time=  27.3s
[CV] END clasificador__max_depth=None, clasificador__max_features=sqrt, clasificador__min_samples_leaf=2, clasificador__min_samples_split=2, clasificador__n_estimators=200; total time=  39.1s
[CV] END clasificador__max_depth=None, clasificador__max_features=sqrt, clasificador__min_samples_leaf=2, clasificador__min_samples_split=2, clasificador__n_estimators=200; total time=  41.5s
[CV] END clasificador__max_depth=None, clasificador__max_features=sqrt, clasificador__min_samples_leaf=2, clasificador__min_samples_split=2, clasificador__n_estimators=200; total time=  39.2s
[CV] END clasificador__max_depth=40, clasificador__max_features=log2, clasificador__min_samples_leaf=2, clasificador__min_samples_split=5, clasificador__n_estimators=150; total time=  28.5s
[CV] END clasificador__max_depth=40, clasificador__max_features=log2, clasificador__min_samples_leaf=2, clasificador__min_samples_split=5, clasificador__n_estimators=150; total time=  29.4s
[CV] END clasificador__max_depth=40, clasificador__max_features=log2, clasificador__min_samples_leaf=2, clasificador__min_samples_split=5, clasificador__n_estimators=150; total time=  31.1s
[CV] END clasificador__max_depth=30, clasificador__max_features=log2, clasificador__min_samples_leaf=2, clasificador__min_samples_split=2, clasificador__n_estimators=150; total time=  30.0s
[CV] END clasificador__max_depth=30, clasificador__max_features=log2, clasificador__min_samples_leaf=2, clasificador__min_samples_split=2, clasificador__n_estimators=150; total time=  30.6s
[CV] END clasificador__max_depth=30, clasificador__max_features=log2, clasificador__min_samples_leaf=2, clasificador__min_samples_split=2, clasificador__n_estimators=150; total time=  28.8s
[CV] END clasificador__max_depth=20, clasificador__max_features=sqrt, clasificador__min_samples_leaf=1, clasificador__min_samples_split=2, clasificador__n_estimators=150; total time=  28.0s
[CV] END clasificador__max_depth=20, clasificador__max_features=sqrt, clasificador__min_samples_leaf=1, clasificador__min_samples_split=2, clasificador__n_estimators=150; total time=  29.3s
[CV] END clasificador__max_depth=20, clasificador__max_features=sqrt, clasificador__min_samples_leaf=1, clasificador__min_samples_split=2, clasificador__n_estimators=150; total time=  26.5s
[CV] END clasificador__max_depth=20, clasificador__max_features=sqrt, clasificador__min_samples_leaf=2, clasificador__min_samples_split=5, clasificador__n_estimators=200; total time=  37.3s
[CV] END clasificador__max_depth=20, clasificador__max_features=sqrt, clasificador__min_samples_leaf=2, clasificador__min_samples_split=5, clasificador__n_estimators=200; total time=  36.3s
[CV] END clasificador__max_depth=20, clasificador__max_features=sqrt, clasificador__min_samples_leaf=2, clasificador__min_samples_split=5, clasificador__n_estimators=200; total time=  34.6s

Búsqueda completada en 1313.5 segundos.
Mejor F1 macro (CV interna): 0.6664

Mejores hiperparámetros encontrados:
  n_estimators             : 200
  min_samples_split        : 5
  min_samples_leaf         : 2
  max_features             : log2
  max_depth                : None</code></pre>
</div>
</div>
</section>
<section id="análisis-de-los-hiperparámetros" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="análisis-de-los-hiperparámetros"><span class="header-section-number">5.8</span> Análisis de los Hiperparámetros</h2>
<p>Se visualiza el comportamiento del F1 macro a través de las distintas combinaciones evaluadas por la búsqueda aleatoria. Estas gráficas documentan empíricamente cómo afectan los principales hiperparámetros al desempeño del modelo, validando que la configuración elegida es óptima dentro del espacio explorado.</p>
<div id="3632e8f1" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Resultados de la búsqueda de hiperparámetros"</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener resultados a través del método de la clase</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>tabla_resultados <span class="op">=</span> modelo.resultados_busqueda()</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Todas las configuraciones evaluadas (ordenadas por F1 macro descendente):"</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tabla_resultados.<span class="bu">round</span>(<span class="dv">4</span>).to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Recuperar datos del objeto de búsqueda para las gráficas</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> pd.DataFrame(modelo.busqueda_.cv_results_).sort_values(<span class="st">'mean_test_score'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">5</span>))</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="co"># F1 macro vs. n_estimators</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].scatter(</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    res[<span class="st">'param_clasificador__n_estimators'</span>],</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    res[<span class="st">'mean_test_score'</span>],</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>    s<span class="op">=</span><span class="dv">80</span>, color<span class="op">=</span><span class="st">'steelblue'</span>, edgecolors<span class="op">=</span><span class="st">'black'</span>, alpha<span class="op">=</span><span class="fl">0.8</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">'n_estimators'</span>)</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">'F1 macro (CV interna)'</span>)</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">'F1 macro vs. n_estimators'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a><span class="co"># F1 macro vs. max_depth</span></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>x_md <span class="op">=</span> res[<span class="st">'param_clasificador__max_depth'</span>].fillna(<span class="st">'None'</span>).<span class="bu">apply</span>(<span class="bu">str</span>)</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].scatter(x_md, res[<span class="st">'mean_test_score'</span>],</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>                s<span class="op">=</span><span class="dv">80</span>, color<span class="op">=</span><span class="st">'steelblue'</span>, edgecolors<span class="op">=</span><span class="st">'black'</span>, alpha<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">'max_depth'</span>)</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">'F1 macro (CV interna)'</span>)</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">'F1 macro vs. max_depth'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].tick_params(axis<span class="op">=</span><span class="st">'x'</span>, rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">'Comportamiento del F1 macro en la búsqueda de hiperparámetros'</span>,</span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, y<span class="op">=</span><span class="fl">1.02</span>)</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-38"><a href="#cb18-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar hiperparámetros del Pipeline final</span></span>
<span id="cb18-39"><a href="#cb18-39" aria-hidden="true" tabindex="-1"></a>rf_final <span class="op">=</span> modelo.pipeline_.named_steps[<span class="st">'clasificador'</span>]</span>
<span id="cb18-40"><a href="#cb18-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Pipeline final configurado con los hiperparámetros óptimos."</span>)</span>
<span id="cb18-41"><a href="#cb18-41" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Estructura:"</span>)</span>
<span id="cb18-42"><a href="#cb18-42" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  [1] StandardScaler          → normalización de las 6 variables"</span>)</span>
<span id="cb18-43"><a href="#cb18-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  [2] RandomForestClassifier  → clasificación del nivel de saturación"</span>)</span>
<span id="cb18-44"><a href="#cb18-44" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Hiperparámetros finales del clasificador:"</span>)</span>
<span id="cb18-45"><a href="#cb18-45" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p <span class="kw">in</span> [<span class="st">'n_estimators'</span>, <span class="st">'max_depth'</span>, <span class="st">'min_samples_split'</span>,</span>
<span id="cb18-46"><a href="#cb18-46" aria-hidden="true" tabindex="-1"></a>          <span class="st">'min_samples_leaf'</span>, <span class="st">'max_features'</span>, <span class="st">'class_weight'</span>, <span class="st">'n_jobs'</span>]:</span>
<span id="cb18-47"><a href="#cb18-47" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>p<span class="sc">:&lt;25}</span><span class="ss">: </span><span class="sc">{</span>rf_final<span class="sc">.</span>get_params()[p]<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Resultados de la búsqueda de hiperparámetros

Todas las configuraciones evaluadas (ordenadas por F1 macro descendente):
 n_est max_d  min_spl  min_lf max_ft  F1_macro    std
   200  None        5       2   log2    0.6664 0.0004
   150    40        5       2   log2    0.6661 0.0002
   300  None        2       2   sqrt    0.6658 0.0003
   150    30        5       2   sqrt    0.6657 0.0006
   200  None        2       2   sqrt    0.6653 0.0002
   150    30        2       2   log2    0.6651 0.0003
   300  None        5       1   sqrt    0.6645 0.0002
   200    20        5       2   sqrt    0.6645 0.0012
   150    20        2       1   sqrt    0.6620 0.0003
   200  None        2       1   sqrt    0.6490 0.0004</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="clasificacion_files/figure-html/cell-11-output-2.png" width="1331" height="491" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Pipeline final configurado con los hiperparámetros óptimos.
Estructura:
  [1] StandardScaler          → normalización de las 6 variables
  [2] RandomForestClassifier  → clasificación del nivel de saturación

Hiperparámetros finales del clasificador:
  n_estimators             : 200
  max_depth                : None
  min_samples_split        : 5
  min_samples_leaf         : 2
  max_features             : log2
  class_weight             : balanced
  n_jobs                   : 1</code></pre>
</div>
</div>
<p>El Pipeline final tiene la estructura: <strong>[1] <code>StandardScaler</code></strong> → normalización de las 9 variables predictoras, seguido de <strong>[2] <code>RandomForestClassifier</code></strong> → clasificación del nivel de saturación con los hiperparámetros óptimos encontrados.</p>
</section>
<section id="evaluación-de-rendimiento-y-métricas" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="evaluación-de-rendimiento-y-métricas"><span class="header-section-number">5.9</span> Evaluación de Rendimiento y Métricas</h2>
<section id="justificación-de-métricas-seleccionadas" class="level3" data-number="5.9.1">
<h3 data-number="5.9.1" class="anchored" data-anchor-id="justificación-de-métricas-seleccionadas"><span class="header-section-number">5.9.1</span> Justificación de Métricas Seleccionadas</h3>
<p>Para evaluar la efectividad del modelo en el contexto del STC Metro, se selecciona un conjunto integral de métricas complementarias. En el contexto operativo del Metro, <strong>buscamos un alto recall para la clase Crítico</strong>, ya que es fundamental no perderse los días de máxima saturación para poder anticipar respuestas operativas. Al mismo tiempo, se requiere una <strong>precision razonable</strong> para que las alertas generadas sean confiables y no saturen los sistemas de respuesta. El <strong>F1-Score macro</strong> es la métrica que la búsqueda de hiperparámetros optimizó, garantizando un balance entre precision y recall sin sacrificar el desempeño en ninguna clase.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 70%">
</colgroup>
<thead>
<tr class="header">
<th>Métrica</th>
<th>Relevancia operativa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Accuracy</strong></td>
<td>Desempeño global del sistema; complementa las métricas por clase.</td>
</tr>
<tr class="even">
<td><strong>Precision por clase</strong></td>
<td>De los días predichos como nivel X, ¿cuántos lo eran realmente? Clave para evitar falsas alarmas.</td>
</tr>
<tr class="odd">
<td><strong>Recall por clase</strong></td>
<td>De los días que realmente fueron nivel X, ¿cuántos detectó el modelo? Clave para no perder días Críticos.</td>
</tr>
<tr class="even">
<td><strong>F1-Score macro</strong></td>
<td>Balance entre precision y recall, tratando todas las clases por igual.</td>
</tr>
<tr class="odd">
<td><strong>F1-Score ponderado</strong></td>
<td>Considera el peso de cada clase; útil para evaluar el desempeño global con desbalance.</td>
</tr>
<tr class="even">
<td><strong>Matriz de confusión</strong></td>
<td>Identifica qué clases se confunden entre sí, revelando patrones de error sistemático.</td>
</tr>
<tr class="odd">
<td><strong>Curva ROC y AUC</strong></td>
<td>Capacidad de discriminación por clase en el espacio probabilístico.</td>
</tr>
</tbody>
</table>
</section>
<section id="cálculo-y-presentación-de-métricas" class="level3" data-number="5.9.2">
<h3 data-number="5.9.2" class="anchored" data-anchor-id="cálculo-y-presentación-de-métricas"><span class="header-section-number">5.9.2</span> Cálculo y Presentación de Métricas</h3>
<div id="475e8380" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Evaluación del modelo supervisado con ModeloClasificacion.evaluar()"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>metricas  <span class="op">=</span> modelo.evaluar(X_test, y_test)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>acc_train <span class="op">=</span> modelo.accuracy_entrenamiento(X_train, y_train)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st"> Comparación con la línea base "</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Accuracy (DummyClassifier)    : </span><span class="sc">{</span>dummy_acc<span class="sc">:.4f}</span><span class="ss">  (</span><span class="sc">{</span>dummy_acc<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%)"</span>)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Accuracy (Random Forest)      : </span><span class="sc">{</span>metricas[<span class="st">'accuracy'</span>]<span class="sc">:.4f}</span><span class="ss">  (</span><span class="sc">{</span>metricas[<span class="st">'accuracy'</span>]<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%)"</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Mejora sobre línea base       : +</span><span class="sc">{</span>(metricas[<span class="st">'accuracy'</span>] <span class="op">-</span> dummy_acc)<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss"> pp"</span>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st"> Diagnóstico de sobreajuste "</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Accuracy en entrenamiento : </span><span class="sc">{</span>acc_train<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Accuracy en prueba        : </span><span class="sc">{</span>metricas[<span class="st">'accuracy'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>diff <span class="op">=</span> acc_train <span class="op">-</span> metricas[<span class="st">'accuracy'</span>]</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Diferencia (gap)          : </span><span class="sc">{</span>diff<span class="sc">:.4f}</span><span class="ss">  (</span><span class="sc">{</span>diff<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss"> pp)"</span>)</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> diff <span class="op">&lt;</span> <span class="fl">0.05</span>:</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"  → Gap pequeño: el modelo generaliza correctamente."</span>)</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a><span class="cf">elif</span> diff <span class="op">&lt;</span> <span class="fl">0.12</span>:</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"  → Gap moderado: leve sobreajuste, aceptable en Random Forest."</span>)</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"  → Gap considerable: evaluar regularización adicional."</span>)</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st"> Métricas por clase "</span>)</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>tabla_m <span class="op">=</span> pd.DataFrame({</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Clase'</span>    : NOMBRES_CLASES,</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Precision'</span>: [<span class="ss">f"</span><span class="sc">{</span>p<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> p <span class="kw">in</span> metricas[<span class="st">'precision_por_clase'</span>]],</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Recall'</span>   : [<span class="ss">f"</span><span class="sc">{</span>r<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> r <span class="kw">in</span> metricas[<span class="st">'recall_por_clase'</span>]],</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">'F1-Score'</span> : [<span class="ss">f"</span><span class="sc">{</span>f<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> f <span class="kw">in</span> metricas[<span class="st">'f1_por_clase'</span>]]</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tabla_m.to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st"> Promedios agregados "</span>)</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span><span class="st">'Métrica'</span><span class="sc">:&lt;20}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'Macro'</span><span class="sc">:&gt;10}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'Ponderada'</span><span class="sc">:&gt;12}</span><span class="ss">"</span>)</span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span><span class="st">'Precision'</span><span class="sc">:&lt;20}</span><span class="ss"> </span><span class="sc">{</span>metricas[<span class="st">'precision_macro'</span>]<span class="sc">:&gt;10.4f}</span><span class="ss"> </span><span class="sc">{</span>metricas[<span class="st">'precision_ponderada'</span>]<span class="sc">:&gt;12.4f}</span><span class="ss">"</span>)</span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span><span class="st">'Recall'</span><span class="sc">:&lt;20}</span><span class="ss"> </span><span class="sc">{</span>metricas[<span class="st">'recall_macro'</span>]<span class="sc">:&gt;10.4f}</span><span class="ss"> </span><span class="sc">{</span>metricas[<span class="st">'recall_ponderado'</span>]<span class="sc">:&gt;12.4f}</span><span class="ss">"</span>)</span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span><span class="st">'F1-Score'</span><span class="sc">:&lt;20}</span><span class="ss"> </span><span class="sc">{</span>metricas[<span class="st">'f1_macro'</span>]<span class="sc">:&gt;10.4f}</span><span class="ss"> </span><span class="sc">{</span>metricas[<span class="st">'f1_ponderado'</span>]<span class="sc">:&gt;12.4f}</span><span class="ss">"</span>)</span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st"> Reporte completo de clasificación "</span>)</span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(metricas[<span class="st">'report_texto'</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Evaluación del modelo supervisado con ModeloClasificacion.evaluar()

 Comparación con la línea base 
  Accuracy (DummyClassifier)    : 0.3470  (34.70%)
  Accuracy (Random Forest)      : 0.6910  (69.10%)
  Mejora sobre línea base       : +34.40 pp

 Diagnóstico de sobreajuste 
  Accuracy en entrenamiento : 0.8114
  Accuracy en prueba        : 0.6910
  Diferencia (gap)          : 0.1204  (12.04 pp)
  → Gap considerable: evaluar regularización adicional.

 Métricas por clase 
  Clase Precision Recall F1-Score
   Bajo    0.8221 0.8152   0.8187
  Medio    0.7455 0.6568   0.6983
   Alto    0.5919 0.6004   0.5961
Crítico    0.5619 0.7111   0.6277

 Promedios agregados 
  Métrica                   Macro    Ponderada
  Precision                0.6803       0.6990
  Recall                   0.6959       0.6910
  F1-Score                 0.6852       0.6927

 Reporte completo de clasificación 
              precision    recall  f1-score   support

        Bajo       0.82      0.82      0.82     18139
       Medio       0.75      0.66      0.70     24849
        Alto       0.59      0.60      0.60     17887
     Crítico       0.56      0.71      0.63     10743

    accuracy                           0.69     71618
   macro avg       0.68      0.70      0.69     71618
weighted avg       0.70      0.69      0.69     71618
</code></pre>
</div>
</div>
<p><strong>Interpretación de métricas:</strong></p>
<ul>
<li><strong>Precision:</strong> De todos los días que el modelo predijo como nivel X, ¿qué proporción lo era realmente? Una precision alta en Crítico garantiza que las alertas operativas generadas sean confiables.</li>
<li><strong>Recall:</strong> De todos los días que realmente fueron nivel X, ¿cuántos detectó el modelo? El recall de Crítico es la métrica operativa más importante: un recall bajo implica que el sistema no anticipa los días de máxima saturación.</li>
<li><strong>F1-Score (macro):</strong> Promedio armónico de precision y recall tratando todas las clases por igual. Es la métrica que optimizó la búsqueda de hiperparámetros para no sacrificar el desempeño en las clases menos representadas.</li>
</ul>
</section>
<section id="análisis-e-interpretación-de-resultados" class="level3" data-number="5.9.3">
<h3 data-number="5.9.3" class="anchored" data-anchor-id="análisis-e-interpretación-de-resultados"><span class="header-section-number">5.9.3</span> Análisis e interpretación de resultados</h3>
<p><strong>Desempeño global y comparación con la línea base</strong></p>
<p>El modelo alcanza una <em>accuracy</em> del <strong>69.10 %</strong> en el conjunto de prueba, lo que representa una mejora de <strong>+34.40 puntos porcentuales</strong> sobre el clasificador trivial (34.70 %). Esta diferencia confirma que el modelo aprende patrones contextuales reales del sistema: lograr prácticamente el doble de aciertos que la heurística de “predecir siempre la clase mayoritaria” evidencia una capacidad discriminativa genuina, construida exclusivamente a partir de variables temporales e identificadores de línea y estación, sin utilizar la afluencia del propio día.</p>
<p>La brecha entre <em>accuracy</em> de entrenamiento (81.14 %) y de prueba (69.10 %) es de 12.04 pp, lo que indica un sobreajuste moderado. Este comportamiento es coherente con el uso de <code>max_depth=None</code>, que permite que los árboles crezcan sin restricción de profundidad. En un bosque de esta escala (200 árboles, ~286 000 muestras de entrenamiento) el sobreajuste moderado es esperable y operativamente aceptable dado el nivel de desempeño conseguido.</p>
<p><strong>Desempeño por clase</strong></p>
<p>La clase <strong>Bajo</strong> obtiene el mayor F1-Score (0.82), lo que refleja que los días de baja demanda (afluencia por debajo del percentil 25 histórico de cada estación) forman un grupo claramente diferenciado. Su alta precisión (0.82) y recall (0.82) indican un desempeño simétrico: el modelo los identifica con fiabilidad y no los confunde frecuentemente con otras clases.</p>
<p>La clase <strong>Medio</strong> presenta buen desempeño (F1 = 0.70), aunque con un recall de 0.66 que revela cierta confusión con las clases adyacentes: un 11 % de los días Medio se clasifica erróneamente como Bajo y un 17 % como Alto, consecuencia natural de ser la clase central en la escala ordinal.</p>
<p>La clase <strong>Alto</strong> es la más difícil de clasificar (F1 = 0.60) por estar en la zona de transición entre operación normal elevada y saturación máxima. Su error es bidireccional: el 16.09 % de los días Alto se clasifica como Medio y el 21.99 % como Crítico, indicando que la frontera de decisión entre estas dos clases es inherentemente difusa en el espacio de características contextuales.</p>
<p>La clase <strong>Crítico</strong>, aunque su precisión es la más baja (0.56), su <strong>recall de 0.71</strong> es operativamente positivo. El modelo detecta el 71 % de los días de máxima saturación, a costa de generar algunas falsas alarmas. En el contexto del STC Metro, este compromiso es favorable: no detectar un día crítico (falso negativo) tiene consecuencias operativas más graves que emitir una alerta innecesaria (falso positivo).</p>
<p><strong>Patrón de errores en la Matriz de Confusión</strong></p>
<p>La matriz normalizada revela un patrón estrictamente <strong>near-diagonal</strong>: los errores ocurren casi exclusivamente entre clases adyacentes (Bajo↔︎Medio, Medio↔︎Alto, Alto↔︎Crítico), con confusiones entre clases no adyacentes prácticamente inexistentes (menos del 2.61 % de días Bajo clasificados como Crítico y 1.10 % en dirección inversa). Esta estructura de error es operativamente relevante: cuando el modelo se equivoca, lo hace por un único nivel en la escala ordinal, nunca confunde un día de baja saturación con uno crítico ni viceversa. Esto significa que incluso las predicciones incorrectas conservan valor informativo para la gestión del sistema.</p>
<p><strong>Capacidad discriminativa probabilística (AUC-ROC)</strong></p>
<p>El AUC macro de <strong>0.8943</strong> es notablemente alto en relación con la <em>accuracy</em> de 69.10 %, lo que indica que el modelo posee una sólida capacidad de ordenamiento probabilístico aunque la frontera de decisión entre clases adyacentes genere cierta imprecisión en la clasificación dura. Todos los AUC por clase (estrategia OvR) superan 0.85, confirmando que el clasificador distingue cada nivel de saturación del resto con alta fiabilidad en el espacio de probabilidades. La disparidad entre AUC alto y <em>accuracy</em> moderada es coherente con la naturaleza ordinal del problema: los cuatro niveles son contiguos y la transición entre ellos es gradual, por lo que el modelo estima bien las probabilidades relativas aunque la asignación exacta de etiqueta sea más difícil.</p>
</section>
</section>
<section id="visualización-matriz-de-confusión-y-curva-roc" class="level2" data-number="5.10">
<h2 data-number="5.10" class="anchored" data-anchor-id="visualización-matriz-de-confusión-y-curva-roc"><span class="header-section-number">5.10</span> Visualización: Matriz de Confusión y Curva ROC</h2>
<section id="matriz-de-confusión" class="level3" data-number="5.10.1">
<h3 data-number="5.10.1" class="anchored" data-anchor-id="matriz-de-confusión"><span class="header-section-number">5.10.1</span> Matriz de Confusión</h3>
<p>Exhibimos la matriz de confusión en valores absolutos y normalizados para visualizar claramente el desempeño del modelo en cada clase, identificando dónde se producen los errores de clasificación y su magnitud relativa. Esto es crucial para entender si el modelo tiende a confundir ciertos niveles de saturación entre sí.</p>
<div id="3e9e336e" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>cm <span class="op">=</span> metricas[<span class="st">'confusion_matrix'</span>]</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">6</span>))</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Valores absolutos</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>ConfusionMatrixDisplay(cm, display_labels<span class="op">=</span>NOMBRES_CLASES).plot(</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    ax<span class="op">=</span>axes[<span class="dv">0</span>], cmap<span class="op">=</span><span class="st">'Blues'</span>, values_format<span class="op">=</span><span class="st">'d'</span>, colorbar<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">'Matriz de Confusión — Valores Absolutos'</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>                  fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalizada por fila (recall por clase)</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>cm_n <span class="op">=</span> cm.astype(<span class="st">'float'</span>) <span class="op">/</span> cm.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>)[:, np.newaxis]</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>ConfusionMatrixDisplay(cm_n, display_labels<span class="op">=</span>NOMBRES_CLASES).plot(</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    ax<span class="op">=</span>axes[<span class="dv">1</span>], cmap<span class="op">=</span><span class="st">'Blues'</span>, values_format<span class="op">=</span><span class="st">'.2%'</span>, colorbar<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">'Matriz de Confusión Normalizada (recall por fila)'</span>,</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>                  fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Matriz normalizada — cada celda = </span><span class="sc">% d</span><span class="st">el total real de esa clase:"</span>)</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.DataFrame(</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>    cm_n <span class="op">*</span> <span class="dv">100</span>,</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>    index  <span class="op">=</span>[<span class="ss">f'Real: </span><span class="sc">{</span>c<span class="sc">}</span><span class="ss">'</span>   <span class="cf">for</span> c <span class="kw">in</span> NOMBRES_CLASES],</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span>[<span class="ss">f'Pred: </span><span class="sc">{</span>c<span class="sc">}</span><span class="ss">'</span>   <span class="cf">for</span> c <span class="kw">in</span> NOMBRES_CLASES]</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>).<span class="bu">round</span>(<span class="dv">2</span>).to_string())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="clasificacion_files/figure-html/cell-13-output-1.png" width="1309" height="562" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Matriz normalizada — cada celda = % del total real de esa clase:
               Pred: Bajo  Pred: Medio  Pred: Alto  Pred: Crítico
Real: Bajo          81.52        11.89        3.98           2.61
Real: Medio         11.05        65.68       17.03           6.24
Real: Alto           1.88        16.09       60.04          21.99
Real: Crítico        1.10         5.00       22.80          71.11</code></pre>
</div>
</div>
</section>
<section id="curvas-roc-one-vs-rest-ovr" class="level3" data-number="5.10.2">
<h3 data-number="5.10.2" class="anchored" data-anchor-id="curvas-roc-one-vs-rest-ovr"><span class="header-section-number">5.10.2</span> Curvas ROC — One-vs-Rest (OvR)</h3>
<p>Para la clasificación multiclase se emplea la estrategia <strong>One-vs-Rest</strong>: para cada nivel de saturación se evalúa la capacidad de discriminación del modelo considerando esa clase como positiva y las demás como negativas. Un AUC cercano a 1.0 confirma que el modelo distingue con alta fiabilidad cada nivel de saturación del resto.</p>
<div id="251aa227" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>y_test_bin <span class="op">=</span> label_binarize(y_test, classes<span class="op">=</span>[<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>])</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">6</span>))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>aucs <span class="op">=</span> []</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, (color, nombre) <span class="kw">in</span> <span class="bu">enumerate</span>(<span class="bu">zip</span>(COLORES_CLASES, NOMBRES_CLASES)):</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    fpr, tpr, _ <span class="op">=</span> roc_curve(y_test_bin[:, i], metricas[<span class="st">'y_proba'</span>][:, i])</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    roc_auc     <span class="op">=</span> auc(fpr, tpr)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    aucs.append(roc_auc)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].plot(fpr, tpr, color<span class="op">=</span>color, lw<span class="op">=</span><span class="fl">2.5</span>,</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>                 label<span class="op">=</span><span class="ss">f'</span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss"> (AUC = </span><span class="sc">{</span>roc_auc<span class="sc">:.4f}</span><span class="ss">)'</span>)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot([<span class="dv">0</span>, <span class="dv">1</span>], [<span class="dv">0</span>, <span class="dv">1</span>], <span class="st">'k--'</span>, lw<span class="op">=</span><span class="dv">1</span>, label<span class="op">=</span><span class="st">'Clasificador aleatorio'</span>)</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlim([<span class="dv">0</span>, <span class="dv">1</span>])<span class="op">;</span> axes[<span class="dv">0</span>].set_ylim([<span class="dv">0</span>, <span class="fl">1.05</span>])</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">'Tasa de Falsos Positivos (FPR)'</span>)</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">'Tasa de Verdaderos Positivos (Recall)'</span>)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">'Curvas ROC por clase (OvR)'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(loc<span class="op">=</span><span class="st">'lower right'</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].barh(NOMBRES_CLASES, aucs, color<span class="op">=</span>COLORES_CLASES, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlim([<span class="fl">0.5</span>, <span class="fl">1.01</span>])<span class="op">;</span> axes[<span class="dv">1</span>].set_xlabel(<span class="st">'AUC-ROC'</span>)</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">'AUC-ROC por clase'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, v <span class="kw">in</span> <span class="bu">enumerate</span>(aucs):</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].text(v <span class="op">+</span> <span class="fl">0.003</span>, i, <span class="ss">f'</span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">'</span>, va<span class="op">=</span><span class="st">'center'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">'Análisis ROC — Clasificación de Saturación (Metro CDMX)'</span>,</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, y<span class="op">=</span><span class="fl">1.02</span>)</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>auc_macro <span class="op">=</span> roc_auc_score(y_test_bin, metricas[<span class="st">'y_proba'</span>], multi_class<span class="op">=</span><span class="st">'ovr'</span>, average<span class="op">=</span><span class="st">'macro'</span>)</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>auc_w     <span class="op">=</span> roc_auc_score(y_test_bin, metricas[<span class="st">'y_proba'</span>], multi_class<span class="op">=</span><span class="st">'ovr'</span>, average<span class="op">=</span><span class="st">'weighted'</span>)</span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">  AUC-ROC Macro    (OvR): </span><span class="sc">{</span>auc_macro<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  AUC-ROC Ponderado(OvR): </span><span class="sc">{</span>auc_w<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="clasificacion_files/figure-html/cell-14-output-1.png" width="1521" height="589" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
  AUC-ROC Macro    (OvR): 0.8943
  AUC-ROC Ponderado(OvR): 0.8899</code></pre>
</div>
</div>
<p>Un AUC &gt; 0.5 confirma poder discriminativo real del modelo. El AUC macro de <strong>0.8943</strong> indica que el clasificador separa probabilísticamente cada nivel de saturación del resto con alta fiabilidad para las cuatro clases evaluadas de forma independiente (estrategia OvR).</p>
</section>
</section>
<section id="análisis-de-importancia-de-variables" class="level2" data-number="5.11">
<h2 data-number="5.11" class="anchored" data-anchor-id="análisis-de-importancia-de-variables"><span class="header-section-number">5.11</span> Análisis de Importancia de Variables</h2>
<p>La importancia de variables del Random Forest (disminución promedio de la impureza de Gini) indica qué atributos del STC Metro contribuyen más a las decisiones de clasificación. Se obtiene directamente desde la instancia del modelo a través del método <code>importancia_variables()</code>.</p>
<div id="625b59db" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>imp_df <span class="op">=</span> modelo.importancia_variables()</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Importancia de variables:"</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(imp_df.to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="dv">4</span>))</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>colores_imp <span class="op">=</span> [<span class="st">'#e74c3c'</span> <span class="cf">if</span> i <span class="op">==</span> <span class="dv">0</span> <span class="cf">else</span> <span class="st">'steelblue'</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(imp_df))]</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> ax.barh(</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    imp_df[<span class="st">'Variable'</span>][::<span class="op">-</span><span class="dv">1</span>],</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    imp_df[<span class="st">'Importancia'</span>][::<span class="op">-</span><span class="dv">1</span>],</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span>colores_imp[::<span class="op">-</span><span class="dv">1</span>],</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>    edgecolor<span class="op">=</span><span class="st">'black'</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>ax.set_title(</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Importancia de Variables — Random Forest</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Clasificación del Nivel de Saturación del Metro CDMX'</span>,</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>    fontsize<span class="op">=</span><span class="dv">11</span>, fontweight<span class="op">=</span><span class="st">'bold'</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Importancia (Gini mean decrease)'</span>)</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> bar, val <span class="kw">in</span> <span class="bu">zip</span>(bars, imp_df[<span class="st">'Importancia'</span>][::<span class="op">-</span><span class="dv">1</span>]):</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>    ax.text(val <span class="op">+</span> <span class="fl">0.002</span>, bar.get_y() <span class="op">+</span> bar.get_height()<span class="op">/</span><span class="dv">2</span>,</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f'</span><span class="sc">{</span>val<span class="sc">:.4f}</span><span class="ss">'</span>, va<span class="op">=</span><span class="st">'center'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Importancia de variables:
        Variable  Importancia
estacion_encoded     0.387144
      dia_semana     0.239530
   linea_encoded     0.128888
            anio     0.117153
     mes_encoded     0.094806
     post_boleto     0.011418
lluvia_historica     0.010936
     es_quincena     0.010124
      es_festivo     0.000000</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="clasificacion_files/figure-html/cell-15-output-2.png" width="852" height="367" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretación de la importancia de variables:</strong></p>
<ul>
<li><p><strong><code>estacion_encoded</code> (variable dominante, 38.7 %):</strong> La estación codificada es el predictor más importante porque la variable objetivo se definió mediante percentiles históricos individuales por estación. Al incluir el identificador de estación, el modelo captura implícitamente la escala de demanda y el perfil de capacidad de cada andén: lo que es “alto” para una estación periférica difiere estructuralmente de lo que es “alto” para una estación del centro histórico. Este resultado valida la decisión de construir <code>nivel_saturacion</code> desde percentiles relativos y no absolutos.</p></li>
<li><p><strong><code>dia_semana</code> (segundo lugar, 23.9 %):</strong> El día de la semana es el predictor temporal de mayor poder discriminativo. La demanda del metro exhibe una ciclicidad semanal marcada y consistente entre líneas y estaciones: los días laborables (lunes a viernes) concentran los niveles Alto y Crítico, mientras que sábado y domingo presentan predominantemente niveles Bajo y Medio.</p></li>
<li><p><strong><code>linea_encoded</code> (tercer lugar, 12.9 %):</strong> La línea complementa la codificación de estación, capturando patrones de demanda a nivel de corredor. Las líneas del centro histórico (Líneas 1, 2, 3) presentan distribuciones de saturación estructuralmente distintas de las periféricas (Líneas A, B, 12), lo que aporta información adicional más allá del identificador de estación individual.</p></li>
<li><p><strong><code>anio</code> (cuarto lugar, 11.7 %):</strong> El año registra la evolución longitudinal del sistema: recuperación post-pandemia (2021–2022), normalización (2023) y crecimiento tras las reaperturas de Líneas 12 y 1 (2024–2026). Estas variaciones estructurales modifican los patrones de demanda relativa a lo largo del tiempo y el modelo las captura de forma efectiva.</p></li>
<li><p><strong><code>mes_encoded</code> (quinto lugar, 9.5 %):</strong> La estacionalidad mensual refleja los ciclos de movilidad urbana. Enero y agosto (inicio de semestres escolares) generan mayor demanda que diciembre y julio (vacaciones). Al ser los percentiles estáticos, los meses de alta demanda concentran más días en los niveles Alto y Crítico.</p></li>
<li><p><strong>Variables binarias (<code>post_boleto</code>, <code>lluvia_historica</code>, <code>es_quincena</code>, <code>es_festivo</code>, ~3.3 % combinadas):</strong> Las cuatro variables binarias tienen una contribución mínima en conjunto. Destaca que <code>es_festivo</code> registra <strong>importancia cero</strong>, lo que indica que el efecto de los días festivos sobre la saturación queda completamente absorbido por <code>dia_semana</code> y el resto de variables contextuales. Este resultado sugiere que <code>es_festivo</code> podría ser eliminada en versiones futuras del modelo sin pérdida de desempeño, simplificando el pipeline de preparación de datos.</p></li>
</ul>
</section>
<section id="persistencia-del-modelo-y-demostración-de-reutilización" class="level2" data-number="5.12">
<h2 data-number="5.12" class="anchored" data-anchor-id="persistencia-del-modelo-y-demostración-de-reutilización"><span class="header-section-number">5.12</span> Persistencia del Modelo y Demostración de Reutilización</h2>
<section id="guardado-del-modelo" class="level3" data-number="5.12.1">
<h3 data-number="5.12.1" class="anchored" data-anchor-id="guardado-del-modelo"><span class="header-section-number">5.12.1</span> Guardado del modelo</h3>
<p>El Pipeline completo (que incluye el <code>StandardScaler</code> con sus parámetros de normalización ajustados sobre <code>X_train</code> y el <code>RandomForestClassifier</code> con los hiperparámetros óptimos) se serializa en disco con <code>joblib</code> a través del método <code>guardar_modelo()</code> de la clase <code>ModeloClasificacion</code>.</p>
<div id="b583d295" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>ruta_modelo <span class="op">=</span> <span class="st">"../../models/rf_clasificacion_metro.joblib"</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>ruta_guardada <span class="op">=</span> modelo.guardar_modelo(ruta_modelo)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Persistencia del modelo con ModeloClasificacion.guardar_modelo()"</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">  Archivo guardado en  : </span><span class="sc">{</span>ruta_guardada<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Tamaño del archivo   : </span><span class="sc">{</span>os<span class="sc">.</span>path<span class="sc">.</span>getsize(ruta_guardada) <span class="op">/</span> <span class="dv">1024</span><span class="sc">:.1f}</span><span class="ss"> KB"</span>)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>rf_guardado <span class="op">=</span> modelo.pipeline_.named_steps[<span class="st">'clasificador'</span>]</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">  Contenido serializado:"</span>)</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"    [1] StandardScaler          — media y desviación estándar de X_train"</span>)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"    [2] RandomForestClassifier  — </span><span class="sc">{</span>rf_guardado<span class="sc">.</span>n_estimators<span class="sc">}</span><span class="ss"> árboles con hiperparámetros óptimos"</span>)</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"        max_depth         : </span><span class="sc">{</span>rf_guardado<span class="sc">.</span>max_depth<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"        min_samples_split : </span><span class="sc">{</span>rf_guardado<span class="sc">.</span>min_samples_split<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"        min_samples_leaf  : </span><span class="sc">{</span>rf_guardado<span class="sc">.</span>min_samples_leaf<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"        max_features      : </span><span class="sc">{</span>rf_guardado<span class="sc">.</span>max_features<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"        class_weight      : </span><span class="sc">{</span>rf_guardado<span class="sc">.</span>class_weight<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Persistencia del modelo con ModeloClasificacion.guardar_modelo()

  Archivo guardado en  : ../../models/rf_clasificacion_metro.joblib
  Tamaño del archivo   : 1714763.3 KB

  Contenido serializado:
    [1] StandardScaler          — media y desviación estándar de X_train
    [2] RandomForestClassifier  — 200 árboles con hiperparámetros óptimos
        max_depth         : None
        min_samples_split : 5
        min_samples_leaf  : 2
        max_features      : log2
        class_weight      : balanced</code></pre>
</div>
</div>
</section>
<section id="demostración-de-reutilización-celda-independiente" class="level3" data-number="5.12.2">
<h3 data-number="5.12.2" class="anchored" data-anchor-id="demostración-de-reutilización-celda-independiente"><span class="header-section-number">5.12.2</span> Demostración de reutilización (celda independiente)</h3>
<p>La siguiente celda es <strong>funcionalmente independiente</strong> del entrenamiento: utiliza únicamente el método de clase <code>ModeloClasificacion.cargar_modelo()</code> para reconstruir el modelo desde disco y realizar predicciones sin acceso a las variables de entrenamiento originales. Esto simula una sesión de inferencia en producción.</p>
<div id="25d4914c" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> gc</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Liberar la memoria del modelo de entrenamiento</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="st">'modelo'</span> <span class="kw">in</span> <span class="bu">locals</span>():</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="kw">del</span> modelo</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>gc.collect()</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── DEMOSTRACIÓN DE REUTILIZACIÓN ───────────────────────────────────────────</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Esta celda simula una sesión de inferencia separada del entrenamiento.</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Solo se necesita la ruta del archivo .joblib y la definición de la clase.</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co"># ─────────────────────────────────────────────────────────────────────────────</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Demostración de reutilización del modelo serializado"</span>)</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>modelo_cargado <span class="op">=</span> ModeloClasificacion.cargar_modelo(ruta_modelo, seed<span class="op">=</span>SEED)</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Pipeline cargado desde : </span><span class="sc">{</span>ruta_modelo<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Instancia recuperada   : </span><span class="sc">{</span>modelo_cargado<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Registros hipotéticos con las 9 variables predictoras</span></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Columnas: linea, estacion, dia_sem, mes, anio, festivo, quincena, lluvia, post_boleto</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>nuevos <span class="op">=</span> pd.DataFrame({</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">'linea_encoded'</span>   : [<span class="dv">0</span>,     <span class="dv">3</span>,     <span class="dv">10</span>,    <span class="dv">7</span>,     <span class="dv">2</span>   ], <span class="co"># Líneas reales del dataset (L1=0, L2=1, etc.)</span></span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">'estacion_encoded'</span>: [<span class="dv">114</span>,   <span class="dv">56</span>,    <span class="dv">142</span>,   <span class="dv">88</span>,    <span class="dv">33</span>  ], <span class="co"># Estaciones </span></span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">'dia_semana'</span>      : [<span class="dv">0</span>,     <span class="dv">4</span>,     <span class="dv">6</span>,     <span class="dv">2</span>,     <span class="dv">1</span>   ], <span class="co"># 0=Lun, 4=Vie, 6=Dom</span></span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">'mes_encoded'</span>     : [<span class="dv">3</span>,     <span class="dv">1</span>,     <span class="dv">5</span>,     <span class="dv">9</span>,     <span class="dv">2</span>   ], <span class="co"># 3=Ene, 1=Ago, 5=Jul</span></span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">'anio'</span>            : [<span class="dv">2025</span>,  <span class="dv">2024</span>,  <span class="dv">2024</span>,  <span class="dv">2023</span>,  <span class="dv">2025</span>], <span class="co"># Años </span></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">'es_festivo'</span>      : [<span class="dv">0</span>,     <span class="dv">0</span>,     <span class="dv">0</span>,     <span class="dv">1</span>,     <span class="dv">1</span>   ], <span class="co"># Los últimos dos son festivos</span></span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">'es_quincena'</span>     : [<span class="dv">1</span>,     <span class="dv">1</span>,     <span class="dv">0</span>,     <span class="dv">0</span>,     <span class="dv">1</span>   ], <span class="co"># Quincenas en regs 1, 2 y 5</span></span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">'lluvia_historica'</span>: [<span class="dv">0</span>,     <span class="dv">1</span>,     <span class="dv">1</span>,     <span class="dv">0</span>,     <span class="dv">0</span>   ], <span class="co"># Lluvia en meses 1 y 5 (Ago y Jul)</span></span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">'post_boleto'</span>     : [<span class="dv">1</span>,     <span class="dv">1</span>,     <span class="dv">1</span>,     <span class="dv">0</span>,     <span class="dv">1</span>   ]  <span class="co"># Todos después de la implementación del boleto digital</span></span>
<span id="cb31-30"><a href="#cb31-30" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb31-31"><a href="#cb31-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-32"><a href="#cb31-32" aria-hidden="true" tabindex="-1"></a>contexto <span class="op">=</span> [</span>
<span id="cb31-33"><a href="#cb31-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">"L1 · Est. 114 · Lun (Ene 2025) · Quincena, Sin lluvia"</span>,</span>
<span id="cb31-34"><a href="#cb31-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">"L3 · Est. 56  · Vie (Ago 2024) · Quincena, Lluvia"</span>,</span>
<span id="cb31-35"><a href="#cb31-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">"LA · Est. 142 · Dom (Jul 2024) · Fin de mes, Lluvia"</span>,</span>
<span id="cb31-36"><a href="#cb31-36" aria-hidden="true" tabindex="-1"></a>    <span class="st">"L7 · Est. 88  · Mié (Nov 2023) · Festivo (Revolución)"</span>,</span>
<span id="cb31-37"><a href="#cb31-37" aria-hidden="true" tabindex="-1"></a>    <span class="st">"L2 · Est. 33  · Mar (Dic 2025) · Festivo, Quincena"</span></span>
<span id="cb31-38"><a href="#cb31-38" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb31-39"><a href="#cb31-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-40"><a href="#cb31-40" aria-hidden="true" tabindex="-1"></a>predicciones   <span class="op">=</span> modelo_cargado.predecir(nuevos)</span>
<span id="cb31-41"><a href="#cb31-41" aria-hidden="true" tabindex="-1"></a>probabilidades <span class="op">=</span> modelo_cargado.predecir_proba(nuevos)</span>
<span id="cb31-42"><a href="#cb31-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-43"><a href="#cb31-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span><span class="st">'Reg'</span><span class="sc">:&lt;4}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'Contexto'</span><span class="sc">:&lt;55}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'Nivel Predicho'</span><span class="sc">:&lt;16}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'Confianza'</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb31-44"><a href="#cb31-44" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  "</span> <span class="op">+</span> <span class="st">"─"</span> <span class="op">*</span> <span class="dv">88</span>)</span>
<span id="cb31-45"><a href="#cb31-45" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, (pred, proba, ctx) <span class="kw">in</span> <span class="bu">enumerate</span>(<span class="bu">zip</span>(predicciones, probabilidades, contexto)):</span>
<span id="cb31-46"><a href="#cb31-46" aria-hidden="true" tabindex="-1"></a>    nivel  <span class="op">=</span> ModeloClasificacion.NOMBRES_CLASES[pred]</span>
<span id="cb31-47"><a href="#cb31-47" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>i<span class="sc">:&lt;4}</span><span class="ss"> </span><span class="sc">{</span>ctx<span class="sc">:&lt;55}</span><span class="ss"> </span><span class="sc">{</span>nivel<span class="sc">:&lt;16}</span><span class="ss"> </span><span class="sc">{</span>proba<span class="sc">.</span><span class="bu">max</span>()<span class="op">*</span><span class="dv">100</span><span class="sc">:&gt;7.1f}</span><span class="ss">%"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Demostración de reutilización del modelo serializado
Modelo cargado desde ../../models/rf_clasificacion_metro.joblib
  Pipeline cargado desde : ../../models/rf_clasificacion_metro.joblib
  Instancia recuperada   : Modelo: ModeloClasificacion, Estado: Entrenado, Características: None

  Reg  Contexto                                                Nivel Predicho   Confianza
  ────────────────────────────────────────────────────────────────────────────────────────
  0    L1 · Est. 114 · Lun (Ene 2025) · Quincena, Sin lluvia   Bajo                50.4%
  1    L3 · Est. 56  · Vie (Ago 2024) · Quincena, Lluvia       Alto                59.9%
  2    LA · Est. 142 · Dom (Jul 2024) · Fin de mes, Lluvia     Bajo                95.4%
  3    L7 · Est. 88  · Mié (Nov 2023) · Festivo (Revolución)   Alto                79.1%
  4    L2 · Est. 33  · Mar (Dic 2025) · Festivo, Quincena      Medio               39.8%</code></pre>
</div>
</div>
<p>La demostración confirma que el Pipeline cargado aplica automáticamente la normalización aprendida en entrenamiento y clasifica el nivel de saturación sin necesidad de re-entrenamiento ni acceso a los datos originales. El objeto <code>ModeloClasificacion</code> queda disponible para inferencia en tiempo real en cualquier módulo de producción que importe el archivo <code>.joblib</code>, verificando el requisito técnico de persistencia del proyecto.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./eda.html" class="pagination-link" aria-label="EDA — Análisis Exploratorio de Datos">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">EDA — Análisis Exploratorio de Datos</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./clustering.html" class="pagination-link" aria-label="Clustering — Agrupamiento de Estaciones">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Clustering — Agrupamiento de Estaciones</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>